name: Apply Infrastructure changes

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: tf-infra-experiment

jobs:
  apply:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - id: 'auth'
        name: Configure GCP credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: projects/518432764157/locations/global/workloadIdentityPools/github/providers/my-repo
      
      - name: Apply to Google Cloud
        run: |
          terraform init -input=true
          terraform state list
          terraform plan
          terraform apply-auto-approve
